service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: femasters
  region: eu-west-2
  stage: dev

plugins:
  - serverless-offline

functions:  
  todos:
    handler: src/api/api.handler
    events:
      - http: ANY /
      - http: 'ANY /{param+}'

  # todo:
  #   handler: src/api/todo.handler
  #   events:
  #     - http:
  #         path: todo/{todo}
  #         method: get
  #         request:
  #           parameters:
  #             paths:
  #               todo: true
